# Generated by Django 5.0.2 on 2024-02-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbiq_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='status',
            new_name='approved',
        ),
    ]
