# Generated by Django 5.0.2 on 2024-02-29 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbiq_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.ManyToManyField(related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
