# Generated by Django 5.0.2 on 2024-02-29 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbiq_api', '0002_remove_employee_photo_alter_task_assign_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_former_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='university',
        ),
    ]
